markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 12
paginate_path: page/:num

blog:
    name: 123
    description: Perfect
    title: shige
    url: http://cuifengfeng.github.com 
    # duoshuo: 
    # tongji: 
author:
    # Profile links on the left sidebar, leave blank to ignore
    name: Perfect
    email: cuifeng_feng@126.com 
    weibo: 1749992905  # weibo ID
    github: cuifengfeng  # github ID
    # gplus: 110552447039675960964
    logo: http://cuifengfeng.github.com/res/img/logo.png

